### ISSUE TITLE
Installation Create "empty file" in node_modules\react-simple-animate directory

### ISSUE THREAD

**Issue by Maxblake** [bluebill1049/react-smooth-range-input#12]
Thanks for making this great slider.  Just small question. After completing the installation I found empty file (0 bytes) in node_modules\react-simple-animate. I can't even delete that file from disk. Any ideas how to to resolve this matter ?
![rsa](https://user-images.githubusercontent.com/18447545/65997572-88525a00-e491-11e9-83f8-9ccf8746857d.jpg)

**Comment by bluebill1049** [comment]
thansk @Maxblake i will take a look at this

**Comment by bluebill1049** [comment]
<img width="562" alt="Screen Shot 2019-10-02 at 9 52 05 am" src="https://user-images.githubusercontent.com/10513364/66008552-55907c00-e4fa-11e9-9f73-1c95fb8a41aa.png">

looks fine at our project, I think the issue is caused by react-simple-animate is a peer dependency, and your project probably is not using react simple animate I think it should be ok.

**Comment by Maxblake** [comment]
Yes, problem is with react-simple-animate. I did new installation. First i install react-simple-animated and after react-smooth-range-input. Same empty file was created in react-simple-animated. How I can avoid this? 
Steps to reproduce:
1. npx create-react-app my-app
2. cd my-app
3.yarn add react-simple-animate
4. yarn add react-smooth-range-input

**Comment by bluebill1049** [comment]
curious to know what issue this is causing?

**Comment by Maxblake** [comment]
Is not issue yet, and I i hope nothing bad will happen when I will move my project to shell.  I don't like surprises. If there was already created 0 bytes file during installation, what else can happen ? A bit of not so serious for repository with 234 stars. I've already deleted that file using command line, so don't worry about it. However, in the future if you figure out why that file was created, will be great to know where was issue.

**Comment by bluebill1049** [comment]
sure will keep you updated in here
